# Generated by Django 4.1.5 on 2023-01-31 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=255)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(default=0)),
                ('role_name', models.CharField(max_length=255)),
                ('role_display_name', models.CharField(max_length=255)),
                ('users', models.ManyToManyField(to='adminManagement.user')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.IntegerField(default=0)),
                ('robot_name', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('working_time', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(to='adminManagement.user')),
            ],
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege_id', models.IntegerField(default=0)),
                ('privilege_name', models.CharField(max_length=255)),
                ('role', models.ManyToManyField(to='adminManagement.role')),
            ],
        ),
        migrations.CreateModel(
            name='GolfRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golf_range_id', models.IntegerField(default=0)),
                ('golf_range_name', models.CharField(max_length=255)),
                ('golf_range_address', models.CharField(max_length=255)),
                ('golf_range_area', models.IntegerField(default=0)),
                ('golf_range_staff_number', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(to='adminManagement.user')),
            ],
        ),
    ]
